name 'rlenglet-locales'
version '0.1.0'
source 'https://github.com/rlenglet/puppet-locales.git'
project_page 'https://github.com/rlenglet/puppet-locales'
author 'Romain Lenglet'
license 'Apache License, Version 2.0'
summary 'System locales configuration'
description 'Configures the system locales'
dependency 'rlenglet/debconf_package', '>= 0.1.0'
